[package]
name = "wgpu-prac-v2"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.16.3"
clap = { version = "4.5.13", features = ["derive"] }
flume = "0.11.0"
log = "0.4.22"
pollster = "0.3.0"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
wgpu = "22.1.0"
